# Generated by Django 4.2.28 on 2026-02-28 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: 8(XXX)XXX-XX-XX или +7 (XXX) XXX-XX-XX', regex='^(8\\(\\d{3}\\)\\d{3}-\\d{2}-\\d{2}|\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2})$')], verbose_name='Телефон'),
        ),
    ]
