# Generated by Django 4.2.28 on 2026-02-28 02:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=32, validators=[main.models.CustomUser.phone_flex_validator], verbose_name='Телефон'),
        ),
    ]
